### ISSUE TITLE
Why is custom CMK needed?

### ISSUE THREAD

**Issue by ceefour** [vacasaoss/serverless-secret-baker#39]
**Is your feature request related to a problem? Please describe.**
Why is custom CMK needed?

**Describe the solution you'd like**
Support also default CMK.

**Describe alternatives you've considered**
I don't know the reason why custom CMK is needed.

**Additional context**

See @piohhmy's blog post: https://dannyvarner.com/2018/12/24/serverless-secrets.html
It seems to imply using default CMK is possible.

**Comment by cruisercohen** [comment]
Hi @ceefour. My understanding is that you can't change the key policy on an AWS managed key, so the lambda function will not be able to decrypt the secret value because the lambda will not have access to the AWS managed key.

https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying.html
> You can view the key policy for an AWS managed CMK or a customer managed CMK, but you can only change the key policy for a customer managed CMK. The policies of AWS managed CMKs are created and managed by the AWS service that created the CMK in your account.

**Comment by ceefour** [comment]
Thnqks @cruisercohen !
